MODEL:
  META_ARCHITECTURE: "fcn16s"

  BACKBONE:
    PRETRAINED: False

  REFINEMENT:
    NAME: ''

DATASETS:
  ROOT: '../dataset/'


TEST:
  WEIGHT: '../ertiaM/checkpoints/train_fcn16s/fcn_model_8.pth'

OUTPUT_DIR: "../ertiaM/checkpoints/inference_fcn16s"

