MODEL:
  META_ARCHITECTURE: "fcn8s"

  BACKBONE:
    PRETRAINED: False

  REFINEMENT:
    NAME: ''

DATASETS:
  ROOT: '../dataset/DDTI'


TEST:
  WEIGHT: '../ertiaM/checkpoints/train_fcn8s/fcn_model_7.pth'

OUTPUT_DIR: "../ertiaM/checkpoints/inference_fcn8s"

