MODEL:
  META_ARCHITECTURE: "fcn8s"

  BACKBONE:
    PRETRAINED: False

  REFINEMENT:
    NAME: ''

DATASETS:
  ROOT: '../dataset'


TEST:
  WEIGHT: '../ertiaM/checkpoints/train_fcn8s_atonce/fcn_model_13.pth'

OUTPUT_DIR: "../ertiaM/checkpoints/inference_fcn8s_atonce"

