MODEL:
  META_ARCHITECTURE: "fcn32s"

  BACKBONE:
    PRETRAINED: False

  REFINEMENT:
    NAME: ''

DATASETS:
  ROOT: '../dataset/'


TEST:
  WEIGHT: '../ertiaM/checkpoints/train_fcn32s/fcn_model_13.pth'

OUTPUT_DIR: "../ertiaM/checkpoints/inference_fcn32s"

