
MODEL:
  META_ARCHITECTURE: "fcn32s"

  BACKBONE:
    PRETRAINED: True
    WEIGHT: '../ertiaM/model_zoo/vgg16-397923af.pth'

  REFINEMENT:
    NAME: ''

DATASETS:
  ROOT: '../dataset/DDTI'

SOLVER:
  MAX_EPOCHS: 13
  CHECKPOINT_PERIOD: 13

OUTPUT_DIR: "../ertiaM/checkpoints/train_fcn32s"
